# Generated by Django 5.0.1 on 2024-01-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categy',
            new_name='category',
        ),
    ]
